FROM centos:7.4.1708

ENV TZ=America/Chicago

ENV PKGLIST="bind-utils"

RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime \
    && echo $TZ > /etc/timezone \
    && yum -y install $PKGLIST \
    && yum clean all 

#CMD ["bash"]
CMD ["/scripts/puppet_master_install"]
