#!/bin/bash

DEBUG=0
VERBOSE=1
BASEDIR=.
DOCKERFILE_BASE=$BASEDIR/Dockerfile_Pup
SCRIPTDIR=$BASEDIR/scripts
FUNCS=$BASEDIR/common_funcs.sh
BACKUPDIR=$HOME/backups/lsst-adm01
NETNAME=puptestnet

pup_type=
dockerfile=
imagename=
containername=
hostname=


[[ -f "$FUNCS" ]] || { echo "Cant find file '$FUNCS'"; exit 1
}
.  "$FUNCS"


function sanepath() {
    [[ $DEBUG -eq 1 ]] && set -x
    path=$( readlink -e "$1" )
    if [[ "${#WINDRIVE}" -gt 0 ]] ; then
        echo "$path" \
        | sed -e "s|^/mnt/$WINDRIVE/|${WINDRIVE^}:/|" \
        | sed -e 's|/|\\|g'
    else
        echo "$path"
    fi
}

action=
if [[ $DEBUG -eq 1 ]] ; then
    action=echo
    VERBOSE=1
fi
[[ $VERBOSE -eq 1 ]] && set -x

# Check command line params
[[ $# -ne 1 ]] && croak "Expected 1 cmdline argument, got '$#'"
case "$1" in
    master)
        pup_type=$1
        hostname=puppet
        containername=puppetserver
        ;;
    agent)
        pup_type=$1
        hostname=agent01
        containername=puppetagent
        ;;
    *) croak 'Unknown install type' ;;
esac
imagename="pup${pup_type}"
dockerfile="${DOCKERFILE_BASE}${pup_type}"

# Check if Docker is running on Windows
if docker info --format '{{json .OperatingSystem}}' | grep -qi windows; then
    readlink -e "$BASEDIR" | grep -q '^\/mnt\/[a-z]\/' \
    || croak "Unable to determine drive letter for dir paths for docker on windows"
    WINDRIVE=$( readlink -e "$BASEDIR" | cut -d/ -f3 )
    [[ ${#WINDRIVE} -ne 1 ]] && croak "Windrive '$WINDRIVE' length is not 1"
fi

# Build Docker Image
<$dockerfile $action docker build -t $imagename - \
|| croak 'Docker build failed'

# Verify custom network exists
mk_user_net "$NETNAME"

# Run Pup Master Image
#$action docker run -itd --rm \
$action docker run -itd \
--mount "Type=bind,Source=$(sanepath $SCRIPTDIR),Destination=/scripts,readonly" \
--mount "Type=bind,Source=$(sanepath $BACKUPDIR),Destination=/backups,readonly" \
--network="$NETNAME" \
--hostname="$hostname" \
--name="$containername" \
$imagename
