#!/bin/bash

#set -x

VERBOSE=1
REPO_URL=https://yum.puppetlabs.com/puppetlabs-release-pc1-el-7.noarch.rpm
REQUIRED_PKGS=( bind-utils \
                lsof \
              )
PUPPET=/opt/puppetlabs/bin/puppet
PUPPETSERVER=/opt/puppetlabs/bin/puppetserver
HOSTNAME=$(hostname)
MASTER_HOSTNAME=$HOSTNAME
#DNS_ALT_NAMES=puppet,puppet.lsst.ncsa.edu,adm01.lsst.ncsa.edu,lsst-adm01.ncsa.illinois.edu
#AGENT_ENV=production
#AGENT_SERVER=$HOSTNAME
#AGENT_LOG=/root/puppet_agent.log.$(date "+%Y%m%dT%H%M%S")
APPLY_LOG=/root/puppet_apply.log.$(date "+%Y%m%dT%H%M%S")
BKUP_DIR=/backups

build_type=

function croak {
    echo ERROR: $*
    exit 99
}


function continue_or_exit() {
    [[ -n "$1" ]] && echo "$1"
    echo "Continue?"
    local yn
    select yn in "Yes" "No"; do
        case $yn in
            Yes) return 0;;
            No ) exit 1;;
        esac
    done
}


function log() {
    [[ $VERBOSE -ne 1 ]] && return
    #echo "FUNCNAME ${FUNCNAME[*]}"
    #echo "BASH_SOURCE ${BASH_SOURCE[*]}"
    #echo "BASH_LINENO ${BASH_LINENO[*]}"
    #echo "In $FUNCNAME ... called by ${FUNCNAME[1]}"
    echo "INFO (${BASH_SOURCE[1]} [${BASH_LINENO[0]}] ${FUNCNAME[1]}) $*"
}


function assert_root() {
    log "enter..."
    [[ $EUID -eq 0 ]] || croak 'Must be root'
}


function process_cmdline() {
    log "enter..."
    [[ $# -eq 1 ]] || croak "Expected 1 argument, got '$#'"
    case "$1" in
        server|master)
            build_type=master
            ;;
        client|agent)
            build_type=agent
            ;;
        *)
            croak "Invalid build type: '$1'"
            ;;
    esac
}


function install_required_pkgs() {
    log "enter..."
    refname=
    [[ ${#REQUIRED_PKGS[@]} -gt 0 ]] \
    && yum install -y "${REQUIRED_PKGS[@]}" \
    || croak "install required pkgs failed"
}


function puppet_install {
    log "enter..."
    ls /etc/yum.repos.d/puppetlabs*.repo &>/dev/null \
    || yum -y install $REPO_URL

    local pkglist=()
    [[ "$build_type" == "master" ]] && pkglist+=( puppetserver )
    [[ "$build_type" == "agent" ]] && pkglist+=( puppet-agent )
    yum -y install "${pkglist[@]}"
}


function puppetdb_install {
    log "enter..."
    ls /etc/yum.repos.d/puppetlabs*.repo &>/dev/null \
    || yum -y install $REPO_URL

    $PUPPET module install -i /etc/puppetlabs/code/modules puppetlabs-puppetdb
    yum -y install puppet-client-tools
}


function restore_config_pre {
    log "enter..."
    [[ "$build_type" != 'master' ]] && {
        log "nothing to do for build_type: 'agent'"
        return
    }
    fn=$( ls -t $BKUP_DIR/*_puppet_config.tar.gz | head -1 )
    if [[ -z $fn ]] ; then
        echo "Cant find a puppet_config file in backup dir '$BKUP_DIR'"
        echo "This step will be skipped"
        continue_or_exit 
    else
        tar zxPf $fn -T - <<ENDHERE
/etc/puppetlabs/code/config
/etc/puppetlabs/code/environments
/etc/puppetlabs/puppet/auth.conf
/etc/puppetlabs/puppet/autosign.conf
/etc/puppetlabs/puppet/ssl
ENDHERE
    fi
}


function restore_config_post {
    log "enter..."
    fn=$( ls -t $BKUP_DIR/*_puppet_config.tar.gz | head -1 )
    [[ -n $fn ]] || croak "Cant find a puppet_config file in backup dir '$BKUP_DIR'"
    tar zxPf $fn -T - <<ENDHERE
        /etc/puppetlabs/puppet/puppet.conf
ENDHERE
}


function restore_db {
    log "enter..."
    fn=$( ls -t $BKUP_DIR/*_puppet_db.tar.gz | head -1 )
    [[ -n $fn ]] || croak "Cant find a puppet_db file in backup dir '$BKUP_DIR'"
    $PUPPET db import $fn
}


function configure_ca {
    log "enter..."
    [[ "$build_type" != 'master' ]] && {
        log "nothing to do for build_type: 'agent'"
        return 0
    }
    [[ -d /etc/puppetlabs/puppet/ssl/ca ]] && return 0
    $PUPPET cert list -a
    $PUPPET config set certname $MASTER_HOSTNAME --section master
    $PUPPET certificate generate \
        ${DNS_ALT_NAMES:+--dns-alt-names $DNS_ALT_NAMES} \
        --ca-location local \
        $MASTER_HOSTNAME
    $PUPPET cert sign $MASTER_HOSTNAME --allow-dns-alt-names
    # don't know what this does, but puppetserver won't start otherwise
    $PUPPET certificate find $MASTER_HOSTNAME --ca-location local &>/dev/null
}


function puppetserver {
    log "enter..."
    [[ "$build_type" != 'master' ]] && {
        log "nothing to do for build_type: 'agent'"
        return 0
    }
    #local pupsrvc="$PUPPET resource service puppetserver"
    local action=$1
    case $action in
        *start|reload) 
                $PUPPETSERVER $action
                is_puppetserver_running || croak 'puppetserver not running'
                ;;
        stop)
                $PUPPETSERVER $action
                is_puppetserver_running && croak 'puppetserver still running'
                ;;
        *)
                croak "unknown action '$action'"
    esac
}


function is_puppetserver_running {
    log "enter..."
    lsof -i :8140 &>/dev/null || croak 'puppetserver failed to start'
}


function create_autosign {
    log "enter..."
    fn=$( $PUPPET config print autosign )
    [[ -f $fn ]] && return 0
    cat > $fn <<ENDHERE
*.ncsa.illinois.edu
*.lsst.ncsa.edu
ENDHERE
}


function site_manifest {
    log "enter..."
    action=$1
    fn=$( $PUPPET config print manifest )/site.pp
    case $action in
        create)
                cat > $fn <<ENDHERE
node $HOSTNAME {
    notify { 'Hello World': withpath => true }
}
ENDHERE
                ;;
        update)
                echo "hiera_include('classes')" >> $fn
                ;;
        delete)
                rm $fn
                ;;
        *) croak "unknown action '$action'"
                ;;
    esac
}


function yaml_manifest {
    log "enter..."
    action=$1
    envpath=$( $PUPPET config print environmentpath | cut -d: -f1 )
    env=$( $PUPPET config print environment )
    dir=$envpath/$env/hieradata/nodes
    mkdir -p $dir
    fn=$dir/${HOSTNAME}.yaml
    case $action in
        create)
                cat >$fn <<ENDHERE
---
classes: 
    - puppetdb
    - puppetdb::master::config
ENDHERE
                ;;
        *) croak "unknown action '$action'"
                ;;
    esac
}


function agent_run {
    log "enter..."
    $PUPPET agent --test \
                  --server=$AGENT_SERVER \
                  --environment=$AGENT_ENV \
                  --logdest=$AGENT_LOG
}


####################################################


assert_root
process_cmdline $*
install_required_pkgs
puppet_install
restore_config_pre
configure_ca
#site_manifest create
puppetserver start
#agent_run
#puppetdb_install
#site_manifest update
#yaml_manifest create
#puppetserver restart
#agent_run
##site_manifest delete
##restore_config_post

exec bash
